# Site settings
# Meta tags
title: Homes For Homeies
description: Homes for Homies is a dedicated nonprofit organization committed to supporting the low-income and homeless individuals of the Twin Cities. Our mission is to channel the generosity of our donors to reputable organizations that directly assist those in need, ensuring that every dollar makes a tangible difference. By partnering with local shelters, food banks, and community outreach programs, we strive to create a network of support and resources that empowers individuals to achieve stability and rebuild their lives. Together, we can foster a stronger, more compassionate community.

# Jekyll settings
baseurl: "" # Leave this blank unless your site is located on a subpath, e.g. /blog
url: "https://homesforhomeless.github.io" # Typically http://www.yourdomain.org
sass:
  sass_dir: assets/css/_sass
  style: compressed

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: 
  - README.md
